version: "2"
services:
  herominers-bot:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - TZ=Europe/London      
    volumes:
      - ./nodejs:/home/node/app
    command: "npm start"
